/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.records;


import com.mr.sa.generator.tables.BizAppUser;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizAppUserRecord extends UpdatableRecordImpl<BizAppUserRecord> implements Record17<String, String, String, Boolean, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String> {

    private static final long serialVersionUID = -1487365584;

    /**
     * Setter for <code>sa.biz_app_user.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sa.biz_app_user.role_Id</code>.
     */
    public void setRoleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.role_Id</code>.
     */
    public String getRoleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sa.biz_app_user.username_</code>. 用户名
     */
    public void setUsername_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.username_</code>. 用户名
     */
    public String getUsername_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sa.biz_app_user.enabled_</code>. 是否可用
     */
    public void setEnabled_(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.enabled_</code>. 是否可用
     */
    public Boolean getEnabled_() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>sa.biz_app_user.nickname_</code>. 昵称
     */
    public void setNickname_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.nickname_</code>. 昵称
     */
    public String getNickname_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sa.biz_app_user.password_</code>. 密码
     */
    public void setPassword_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.password_</code>. 密码
     */
    public String getPassword_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sa.biz_app_user.org_id_</code>. 组织ID
     */
    public void setOrgId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.org_id_</code>. 组织ID
     */
    public String getOrgId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sa.biz_app_user.gender_</code>. 性别
     */
    public void setGender_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.gender_</code>. 性别
     */
    public String getGender_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sa.biz_app_user.phone_</code>. 手机号
     */
    public void setPhone_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.phone_</code>. 手机号
     */
    public String getPhone_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sa.biz_app_user.mail_</code>. 邮箱
     */
    public void setMail_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.mail_</code>. 邮箱
     */
    public String getMail_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>sa.biz_app_user.address_</code>. 地址
     */
    public void setAddress_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.address_</code>. 地址
     */
    public String getAddress_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sa.biz_app_user.remark_</code>. 备注
     */
    public void setRemark_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.remark_</code>. 备注
     */
    public String getRemark_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sa.biz_app_user.created_date</code>. 创建日期
     */
    public void setCreatedDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.created_date</code>. 创建日期
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>sa.biz_app_user.creator</code>. 创建人
     */
    public void setCreator(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.creator</code>. 创建人
     */
    public String getCreator() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sa.biz_app_user.update_date</code>. 修改日期
     */
    public void setUpdateDate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.update_date</code>. 修改日期
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>sa.biz_app_user.modifier</code>. 修改人
     */
    public void setModifier(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.modifier</code>. 修改人
     */
    public String getModifier() {
        return (String) get(15);
    }

    /**
     * Setter for <code>sa.biz_app_user.avatar_</code>. 用户头像
     */
    public void setAvatar_(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>sa.biz_app_user.avatar_</code>. 用户头像
     */
    public String getAvatar_() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, String, Boolean, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, String, Boolean, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BizAppUser.BIZ_APP_USER.ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BizAppUser.BIZ_APP_USER.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BizAppUser.BIZ_APP_USER.USERNAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return BizAppUser.BIZ_APP_USER.ENABLED_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BizAppUser.BIZ_APP_USER.NICKNAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BizAppUser.BIZ_APP_USER.PASSWORD_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BizAppUser.BIZ_APP_USER.ORG_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BizAppUser.BIZ_APP_USER.GENDER_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BizAppUser.BIZ_APP_USER.PHONE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return BizAppUser.BIZ_APP_USER.MAIL_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return BizAppUser.BIZ_APP_USER.ADDRESS_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return BizAppUser.BIZ_APP_USER.REMARK_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return BizAppUser.BIZ_APP_USER.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return BizAppUser.BIZ_APP_USER.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field15() {
        return BizAppUser.BIZ_APP_USER.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return BizAppUser.BIZ_APP_USER.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return BizAppUser.BIZ_APP_USER.AVATAR_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUsername_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getEnabled_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNickname_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPassword_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getOrgId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getGender_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPhone_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getMail_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAddress_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getRemark_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component15() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getAvatar_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEnabled_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNickname_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPassword_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getOrgId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getGender_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPhone_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getMail_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAddress_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getRemark_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value15() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getAvatar_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value1(String value) {
        setId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value2(String value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value3(String value) {
        setUsername_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value4(Boolean value) {
        setEnabled_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value5(String value) {
        setNickname_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value6(String value) {
        setPassword_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value7(String value) {
        setOrgId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value8(String value) {
        setGender_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value9(String value) {
        setPhone_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value10(String value) {
        setMail_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value11(String value) {
        setAddress_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value12(String value) {
        setRemark_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value13(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value14(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value15(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value16(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord value17(String value) {
        setAvatar_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizAppUserRecord values(String value1, String value2, String value3, Boolean value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, LocalDateTime value13, String value14, LocalDateTime value15, String value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizAppUserRecord
     */
    public BizAppUserRecord() {
        super(BizAppUser.BIZ_APP_USER);
    }

    /**
     * Create a detached, initialised BizAppUserRecord
     */
    public BizAppUserRecord(String id_, String roleId, String username_, Boolean enabled_, String nickname_, String password_, String orgId_, String gender_, String phone_, String mail_, String address_, String remark_, LocalDateTime createdDate, String creator, LocalDateTime updateDate, String modifier, String avatar_) {
        super(BizAppUser.BIZ_APP_USER);

        set(0, id_);
        set(1, roleId);
        set(2, username_);
        set(3, enabled_);
        set(4, nickname_);
        set(5, password_);
        set(6, orgId_);
        set(7, gender_);
        set(8, phone_);
        set(9, mail_);
        set(10, address_);
        set(11, remark_);
        set(12, createdDate);
        set(13, creator);
        set(14, updateDate);
        set(15, modifier);
        set(16, avatar_);
    }
}
