/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.records;


import com.mr.sa.generator.tables.BizPointTaskItemPoint;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 关系:巡防任务/巡防组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointTaskItemPointRecord extends UpdatableRecordImpl<BizPointTaskItemPointRecord> implements Record9<String, String, String, String, Boolean, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1602484607;

    /**
     * Setter for <code>sa.biz_point_task_item_point.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.point_task_item_id</code>. 巡防任务ID
     */
    public void setPointTaskItemId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.point_task_item_id</code>. 巡防任务ID
     */
    public String getPointTaskItemId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.org_id</code>.
     */
    public void setOrgId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.org_id</code>.
     */
    public String getOrgId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.point_id</code>. 巡防点ID
     */
    public void setPointId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.point_id</code>. 巡防点ID
     */
    public String getPointId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.required</code>. 是否为必扫点
     */
    public void setRequired(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.required</code>. 是否为必扫点
     */
    public Boolean getRequired() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.created_date</code>. 创建日期
     */
    public void setCreatedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.created_date</code>. 创建日期
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.creator</code>. 创建人
     */
    public void setCreator(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.creator</code>. 创建人
     */
    public String getCreator() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.update_date</code>. 修改日期
     */
    public void setUpdateDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.update_date</code>. 修改日期
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_point.modifier</code>. 修改人
     */
    public void setModifier(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_point.modifier</code>. 修改人
     */
    public String getModifier() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Boolean, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, Boolean, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.POINT_TASK_ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.POINT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.REQUIRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPointTaskItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPointId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getRequired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPointTaskItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPointId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getRequired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value2(String value) {
        setPointTaskItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value3(String value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value4(String value) {
        setPointId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value5(Boolean value) {
        setRequired(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value6(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value7(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value8(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord value9(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPointRecord values(String value1, String value2, String value3, String value4, Boolean value5, LocalDateTime value6, String value7, LocalDateTime value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizPointTaskItemPointRecord
     */
    public BizPointTaskItemPointRecord() {
        super(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT);
    }

    /**
     * Create a detached, initialised BizPointTaskItemPointRecord
     */
    public BizPointTaskItemPointRecord(String id, String pointTaskItemId, String orgId, String pointId, Boolean required, LocalDateTime createdDate, String creator, LocalDateTime updateDate, String modifier) {
        super(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT);

        set(0, id);
        set(1, pointTaskItemId);
        set(2, orgId);
        set(3, pointId);
        set(4, required);
        set(5, createdDate);
        set(6, creator);
        set(7, updateDate);
        set(8, modifier);
    }
}
