/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.records;


import com.mr.sa.generator.tables.BizPointTaskItemOrg;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 关系:巡防任务/巡防组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointTaskItemOrgRecord extends UpdatableRecordImpl<BizPointTaskItemOrgRecord> implements Record7<String, String, String, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 593315518;

    /**
     * Setter for <code>sa.biz_point_task_item_org.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_org.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_org.point_task_item_id</code>. 点任务ID
     */
    public void setPointTaskItemId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_org.point_task_item_id</code>. 点任务ID
     */
    public String getPointTaskItemId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_org.org_id</code>. 组织ID
     */
    public void setOrgId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_org.org_id</code>. 组织ID
     */
    public String getOrgId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_org.created_date</code>. 创建日期
     */
    public void setCreatedDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_org.created_date</code>. 创建日期
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_org.creator</code>. 创建人
     */
    public void setCreator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_org.creator</code>. 创建人
     */
    public String getCreator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_org.update_date</code>. 修改日期
     */
    public void setUpdateDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_org.update_date</code>. 修改日期
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sa.biz_point_task_item_org.modifier</code>. 修改人
     */
    public void setModifier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sa.biz_point_task_item_org.modifier</code>. 修改人
     */
    public String getModifier() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.POINT_TASK_ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPointTaskItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPointTaskItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord value2(String value) {
        setPointTaskItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord value3(String value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord value4(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord value5(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord value6(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord value7(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemOrgRecord values(String value1, String value2, String value3, LocalDateTime value4, String value5, LocalDateTime value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizPointTaskItemOrgRecord
     */
    public BizPointTaskItemOrgRecord() {
        super(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG);
    }

    /**
     * Create a detached, initialised BizPointTaskItemOrgRecord
     */
    public BizPointTaskItemOrgRecord(String id, String pointTaskItemId, String orgId, LocalDateTime createdDate, String creator, LocalDateTime updateDate, String modifier) {
        super(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG);

        set(0, id);
        set(1, pointTaskItemId);
        set(2, orgId);
        set(3, createdDate);
        set(4, creator);
        set(5, updateDate);
        set(6, modifier);
    }
}
