/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.records;


import com.mr.sa.generator.tables.BizPatrolPoint;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 巡防点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPatrolPointRecord extends UpdatableRecordImpl<BizPatrolPointRecord> implements Record14<String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, String, String> {

    private static final long serialVersionUID = -731594960;

    /**
     * Setter for <code>sa.biz_patrol_point.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.code</code>. 编码
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.code</code>. 编码
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.name</code>. 名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.name</code>. 名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.longitude</code>. 经度
     */
    public void setLongitude(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.longitude</code>. 经度
     */
    public String getLongitude() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.latitude</code>. 纬度
     */
    public void setLatitude(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.latitude</code>. 纬度
     */
    public String getLatitude() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.qrcode_url</code>.
     */
    public void setQrcodeUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.qrcode_url</code>.
     */
    public String getQrcodeUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.qr_code</code>. 二维码编码
     */
    public void setQrCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.qr_code</code>. 二维码编码
     */
    public String getQrCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.created_date</code>. 创建日期
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.created_date</code>. 创建日期
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.creator</code>. 创建人
     */
    public void setCreator(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.creator</code>. 创建人
     */
    public String getCreator() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.update_date</code>. 修改日期
     */
    public void setUpdateDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.update_date</code>. 修改日期
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.modifier</code>. 修改人
     */
    public void setModifier(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.modifier</code>. 修改人
     */
    public String getModifier() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.org_id</code>.
     */
    public void setOrgId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.org_id</code>.
     */
    public String getOrgId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.level</code>. 1:1级巡防点, 2:2级巡防点
     */
    public void setLevel(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.level</code>. 1:1级巡防点, 2:2级巡防点
     */
    public String getLevel() {
        return (String) get(12);
    }

    /**
     * Setter for <code>sa.biz_patrol_point.type</code>. 扫码点: scan_point，立岗点: sentry_point，盘查点: inspect_point
     */
    public void setType(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sa.biz_patrol_point.type</code>. 扫码点: scan_point，立岗点: sentry_point，盘查点: inspect_point
     */
    public String getType() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BizPatrolPoint.BIZ_PATROL_POINT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BizPatrolPoint.BIZ_PATROL_POINT.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BizPatrolPoint.BIZ_PATROL_POINT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BizPatrolPoint.BIZ_PATROL_POINT.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BizPatrolPoint.BIZ_PATROL_POINT.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BizPatrolPoint.BIZ_PATROL_POINT.QRCODE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BizPatrolPoint.BIZ_PATROL_POINT.QR_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return BizPatrolPoint.BIZ_PATROL_POINT.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BizPatrolPoint.BIZ_PATROL_POINT.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return BizPatrolPoint.BIZ_PATROL_POINT.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return BizPatrolPoint.BIZ_PATROL_POINT.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return BizPatrolPoint.BIZ_PATROL_POINT.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return BizPatrolPoint.BIZ_PATROL_POINT.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return BizPatrolPoint.BIZ_PATROL_POINT.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getQrcodeUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getQrCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getQrcodeUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getQrCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value4(String value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value5(String value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value6(String value) {
        setQrcodeUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value7(String value) {
        setQrCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value8(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value9(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value10(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value11(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value12(String value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value13(String value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord value14(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPointRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, String value9, LocalDateTime value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizPatrolPointRecord
     */
    public BizPatrolPointRecord() {
        super(BizPatrolPoint.BIZ_PATROL_POINT);
    }

    /**
     * Create a detached, initialised BizPatrolPointRecord
     */
    public BizPatrolPointRecord(String id, String code, String name, String longitude, String latitude, String qrcodeUrl, String qrCode, LocalDateTime createdDate, String creator, LocalDateTime updateDate, String modifier, String orgId, String level, String type) {
        super(BizPatrolPoint.BIZ_PATROL_POINT);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, longitude);
        set(4, latitude);
        set(5, qrcodeUrl);
        set(6, qrCode);
        set(7, createdDate);
        set(8, creator);
        set(9, updateDate);
        set(10, modifier);
        set(11, orgId);
        set(12, level);
        set(13, type);
    }
}
