/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.records;


import com.mr.sa.generator.tables.BizUserKeepOnlineTime;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizUserKeepOnlineTimeRecord extends UpdatableRecordImpl<BizUserKeepOnlineTimeRecord> implements Record7<String, String, String, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -769920483;

    /**
     * Setter for <code>sa.biz_user_keep_online_time.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sa.biz_user_keep_online_time.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sa.biz_user_keep_online_time.user_id</code>. 用户id
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sa.biz_user_keep_online_time.user_id</code>. 用户id
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sa.biz_user_keep_online_time.user_name</code>. 用户名称
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sa.biz_user_keep_online_time.user_name</code>. 用户名称
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sa.biz_user_keep_online_time.org_id</code>. 单位id
     */
    public void setOrgId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sa.biz_user_keep_online_time.org_id</code>. 单位id
     */
    public String getOrgId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sa.biz_user_keep_online_time.online_second</code>. 在线巡逻时长
     */
    public void setOnlineSecond(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sa.biz_user_keep_online_time.online_second</code>. 在线巡逻时长
     */
    public Integer getOnlineSecond() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sa.biz_user_keep_online_time.record_date</code>. 记录日期
     */
    public void setRecordDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sa.biz_user_keep_online_time.record_date</code>. 记录日期
     */
    public LocalDateTime getRecordDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sa.biz_user_keep_online_time.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>sa.biz_user_keep_online_time.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ONLINE_SECOND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.RECORD_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getOnlineSecond();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getRecordDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getOnlineSecond();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getRecordDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord value3(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord value4(String value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord value5(Integer value) {
        setOnlineSecond(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord value6(LocalDateTime value) {
        setRecordDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserKeepOnlineTimeRecord values(String value1, String value2, String value3, String value4, Integer value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizUserKeepOnlineTimeRecord
     */
    public BizUserKeepOnlineTimeRecord() {
        super(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME);
    }

    /**
     * Create a detached, initialised BizUserKeepOnlineTimeRecord
     */
    public BizUserKeepOnlineTimeRecord(String id, String userId, String userName, String orgId, Integer onlineSecond, LocalDateTime recordDate, LocalDateTime createTime) {
        super(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME);

        set(0, id);
        set(1, userId);
        set(2, userName);
        set(3, orgId);
        set(4, onlineSecond);
        set(5, recordDate);
        set(6, createTime);
    }
}
