/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 用户
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizAppUser implements Serializable {

    private static final long serialVersionUID = -305914311;

    private String        id_;
    private String        roleId;
    private String        username_;
    private Boolean       enabled_;
    private String        nickname_;
    private String        password_;
    private String        orgId_;
    private String        gender_;
    private String        phone_;
    private String        mail_;
    private String        address_;
    private String        remark_;
    private LocalDateTime createdDate;
    private String        creator;
    private LocalDateTime updateDate;
    private String        modifier;
    private String        avatar_;

    public BizAppUser() {}

    public BizAppUser(BizAppUser value) {
        this.id_ = value.id_;
        this.roleId = value.roleId;
        this.username_ = value.username_;
        this.enabled_ = value.enabled_;
        this.nickname_ = value.nickname_;
        this.password_ = value.password_;
        this.orgId_ = value.orgId_;
        this.gender_ = value.gender_;
        this.phone_ = value.phone_;
        this.mail_ = value.mail_;
        this.address_ = value.address_;
        this.remark_ = value.remark_;
        this.createdDate = value.createdDate;
        this.creator = value.creator;
        this.updateDate = value.updateDate;
        this.modifier = value.modifier;
        this.avatar_ = value.avatar_;
    }

    public BizAppUser(
        String        id_,
        String        roleId,
        String        username_,
        Boolean       enabled_,
        String        nickname_,
        String        password_,
        String        orgId_,
        String        gender_,
        String        phone_,
        String        mail_,
        String        address_,
        String        remark_,
        LocalDateTime createdDate,
        String        creator,
        LocalDateTime updateDate,
        String        modifier,
        String        avatar_
    ) {
        this.id_ = id_;
        this.roleId = roleId;
        this.username_ = username_;
        this.enabled_ = enabled_;
        this.nickname_ = nickname_;
        this.password_ = password_;
        this.orgId_ = orgId_;
        this.gender_ = gender_;
        this.phone_ = phone_;
        this.mail_ = mail_;
        this.address_ = address_;
        this.remark_ = remark_;
        this.createdDate = createdDate;
        this.creator = creator;
        this.updateDate = updateDate;
        this.modifier = modifier;
        this.avatar_ = avatar_;
    }

    public String getId_() {
        return this.id_;
    }

    public void setId_(String id_) {
        this.id_ = id_;
    }

    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    public String getUsername_() {
        return this.username_;
    }

    public void setUsername_(String username_) {
        this.username_ = username_;
    }

    public Boolean getEnabled_() {
        return this.enabled_;
    }

    public void setEnabled_(Boolean enabled_) {
        this.enabled_ = enabled_;
    }

    public String getNickname_() {
        return this.nickname_;
    }

    public void setNickname_(String nickname_) {
        this.nickname_ = nickname_;
    }

    public String getPassword_() {
        return this.password_;
    }

    public void setPassword_(String password_) {
        this.password_ = password_;
    }

    public String getOrgId_() {
        return this.orgId_;
    }

    public void setOrgId_(String orgId_) {
        this.orgId_ = orgId_;
    }

    public String getGender_() {
        return this.gender_;
    }

    public void setGender_(String gender_) {
        this.gender_ = gender_;
    }

    public String getPhone_() {
        return this.phone_;
    }

    public void setPhone_(String phone_) {
        this.phone_ = phone_;
    }

    public String getMail_() {
        return this.mail_;
    }

    public void setMail_(String mail_) {
        this.mail_ = mail_;
    }

    public String getAddress_() {
        return this.address_;
    }

    public void setAddress_(String address_) {
        this.address_ = address_;
    }

    public String getRemark_() {
        return this.remark_;
    }

    public void setRemark_(String remark_) {
        this.remark_ = remark_;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public String getAvatar_() {
        return this.avatar_;
    }

    public void setAvatar_(String avatar_) {
        this.avatar_ = avatar_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BizAppUser (");

        sb.append(id_);
        sb.append(", ").append(roleId);
        sb.append(", ").append(username_);
        sb.append(", ").append(enabled_);
        sb.append(", ").append(nickname_);
        sb.append(", ").append(password_);
        sb.append(", ").append(orgId_);
        sb.append(", ").append(gender_);
        sb.append(", ").append(phone_);
        sb.append(", ").append(mail_);
        sb.append(", ").append(address_);
        sb.append(", ").append(remark_);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(creator);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(modifier);
        sb.append(", ").append(avatar_);

        sb.append(")");
        return sb.toString();
    }
}
