/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 巡防点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPatrolPoint implements Serializable {

    private static final long serialVersionUID = -1357508648;

    private String        id;
    private String        code;
    private String        name;
    private String        longitude;
    private String        latitude;
    private String        qrcodeUrl;
    private String        qrCode;
    private LocalDateTime createdDate;
    private String        creator;
    private LocalDateTime updateDate;
    private String        modifier;
    private String        orgId;
    private String        level;
    private String        type;

    public BizPatrolPoint() {}

    public BizPatrolPoint(BizPatrolPoint value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.longitude = value.longitude;
        this.latitude = value.latitude;
        this.qrcodeUrl = value.qrcodeUrl;
        this.qrCode = value.qrCode;
        this.createdDate = value.createdDate;
        this.creator = value.creator;
        this.updateDate = value.updateDate;
        this.modifier = value.modifier;
        this.orgId = value.orgId;
        this.level = value.level;
        this.type = value.type;
    }

    public BizPatrolPoint(
        String        id,
        String        code,
        String        name,
        String        longitude,
        String        latitude,
        String        qrcodeUrl,
        String        qrCode,
        LocalDateTime createdDate,
        String        creator,
        LocalDateTime updateDate,
        String        modifier,
        String        orgId,
        String        level,
        String        type
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.longitude = longitude;
        this.latitude = latitude;
        this.qrcodeUrl = qrcodeUrl;
        this.qrCode = qrCode;
        this.createdDate = createdDate;
        this.creator = creator;
        this.updateDate = updateDate;
        this.modifier = modifier;
        this.orgId = orgId;
        this.level = level;
        this.type = type;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLongitude() {
        return this.longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return this.latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getQrcodeUrl() {
        return this.qrcodeUrl;
    }

    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl;
    }

    public String getQrCode() {
        return this.qrCode;
    }

    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BizPatrolPoint (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(longitude);
        sb.append(", ").append(latitude);
        sb.append(", ").append(qrcodeUrl);
        sb.append(", ").append(qrCode);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(creator);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(modifier);
        sb.append(", ").append(orgId);
        sb.append(", ").append(level);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
