/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 巡防活动
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointPlan implements Serializable {

    private static final long serialVersionUID = 1715639434;

    private String        id;
    private String        name;
    private String        orgId;
    private LocalDate     announceTime;
    private LocalDateTime patrolStartTime;
    private LocalDateTime patrolEndTime;
    private Integer       doneRatio;
    private String        workStatus;
    private String        reason;
    private String        pointTaskItemId;
    private String        pointTaskId;
    private Integer       timeInterval;
    private Integer       timeRedundancy;
    private Integer       memberAmount;
    private Integer       copAmount;
    private Integer       apAmount;
    private LocalDateTime createdDate;
    private String        creator;
    private LocalDateTime updateDate;
    private String        modifier;

    public BizPointPlan() {}

    public BizPointPlan(BizPointPlan value) {
        this.id = value.id;
        this.name = value.name;
        this.orgId = value.orgId;
        this.announceTime = value.announceTime;
        this.patrolStartTime = value.patrolStartTime;
        this.patrolEndTime = value.patrolEndTime;
        this.doneRatio = value.doneRatio;
        this.workStatus = value.workStatus;
        this.reason = value.reason;
        this.pointTaskItemId = value.pointTaskItemId;
        this.pointTaskId = value.pointTaskId;
        this.timeInterval = value.timeInterval;
        this.timeRedundancy = value.timeRedundancy;
        this.memberAmount = value.memberAmount;
        this.copAmount = value.copAmount;
        this.apAmount = value.apAmount;
        this.createdDate = value.createdDate;
        this.creator = value.creator;
        this.updateDate = value.updateDate;
        this.modifier = value.modifier;
    }

    public BizPointPlan(
        String        id,
        String        name,
        String        orgId,
        LocalDate     announceTime,
        LocalDateTime patrolStartTime,
        LocalDateTime patrolEndTime,
        Integer       doneRatio,
        String        workStatus,
        String        reason,
        String        pointTaskItemId,
        String        pointTaskId,
        Integer       timeInterval,
        Integer       timeRedundancy,
        Integer       memberAmount,
        Integer       copAmount,
        Integer       apAmount,
        LocalDateTime createdDate,
        String        creator,
        LocalDateTime updateDate,
        String        modifier
    ) {
        this.id = id;
        this.name = name;
        this.orgId = orgId;
        this.announceTime = announceTime;
        this.patrolStartTime = patrolStartTime;
        this.patrolEndTime = patrolEndTime;
        this.doneRatio = doneRatio;
        this.workStatus = workStatus;
        this.reason = reason;
        this.pointTaskItemId = pointTaskItemId;
        this.pointTaskId = pointTaskId;
        this.timeInterval = timeInterval;
        this.timeRedundancy = timeRedundancy;
        this.memberAmount = memberAmount;
        this.copAmount = copAmount;
        this.apAmount = apAmount;
        this.createdDate = createdDate;
        this.creator = creator;
        this.updateDate = updateDate;
        this.modifier = modifier;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public LocalDate getAnnounceTime() {
        return this.announceTime;
    }

    public void setAnnounceTime(LocalDate announceTime) {
        this.announceTime = announceTime;
    }

    public LocalDateTime getPatrolStartTime() {
        return this.patrolStartTime;
    }

    public void setPatrolStartTime(LocalDateTime patrolStartTime) {
        this.patrolStartTime = patrolStartTime;
    }

    public LocalDateTime getPatrolEndTime() {
        return this.patrolEndTime;
    }

    public void setPatrolEndTime(LocalDateTime patrolEndTime) {
        this.patrolEndTime = patrolEndTime;
    }

    public Integer getDoneRatio() {
        return this.doneRatio;
    }

    public void setDoneRatio(Integer doneRatio) {
        this.doneRatio = doneRatio;
    }

    public String getWorkStatus() {
        return this.workStatus;
    }

    public void setWorkStatus(String workStatus) {
        this.workStatus = workStatus;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getPointTaskItemId() {
        return this.pointTaskItemId;
    }

    public void setPointTaskItemId(String pointTaskItemId) {
        this.pointTaskItemId = pointTaskItemId;
    }

    public String getPointTaskId() {
        return this.pointTaskId;
    }

    public void setPointTaskId(String pointTaskId) {
        this.pointTaskId = pointTaskId;
    }

    public Integer getTimeInterval() {
        return this.timeInterval;
    }

    public void setTimeInterval(Integer timeInterval) {
        this.timeInterval = timeInterval;
    }

    public Integer getTimeRedundancy() {
        return this.timeRedundancy;
    }

    public void setTimeRedundancy(Integer timeRedundancy) {
        this.timeRedundancy = timeRedundancy;
    }

    public Integer getMemberAmount() {
        return this.memberAmount;
    }

    public void setMemberAmount(Integer memberAmount) {
        this.memberAmount = memberAmount;
    }

    public Integer getCopAmount() {
        return this.copAmount;
    }

    public void setCopAmount(Integer copAmount) {
        this.copAmount = copAmount;
    }

    public Integer getApAmount() {
        return this.apAmount;
    }

    public void setApAmount(Integer apAmount) {
        this.apAmount = apAmount;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BizPointPlan (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(orgId);
        sb.append(", ").append(announceTime);
        sb.append(", ").append(patrolStartTime);
        sb.append(", ").append(patrolEndTime);
        sb.append(", ").append(doneRatio);
        sb.append(", ").append(workStatus);
        sb.append(", ").append(reason);
        sb.append(", ").append(pointTaskItemId);
        sb.append(", ").append(pointTaskId);
        sb.append(", ").append(timeInterval);
        sb.append(", ").append(timeRedundancy);
        sb.append(", ").append(memberAmount);
        sb.append(", ").append(copAmount);
        sb.append(", ").append(apAmount);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(creator);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(modifier);

        sb.append(")");
        return sb.toString();
    }
}
