/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 关系:巡防任务/巡防组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointTaskItemPoint implements Serializable {

    private static final long serialVersionUID = 949197545;

    private String        id;
    private String        pointTaskItemId;
    private String        orgId;
    private String        pointId;
    private Boolean       required;
    private LocalDateTime createdDate;
    private String        creator;
    private LocalDateTime updateDate;
    private String        modifier;

    public BizPointTaskItemPoint() {}

    public BizPointTaskItemPoint(BizPointTaskItemPoint value) {
        this.id = value.id;
        this.pointTaskItemId = value.pointTaskItemId;
        this.orgId = value.orgId;
        this.pointId = value.pointId;
        this.required = value.required;
        this.createdDate = value.createdDate;
        this.creator = value.creator;
        this.updateDate = value.updateDate;
        this.modifier = value.modifier;
    }

    public BizPointTaskItemPoint(
        String        id,
        String        pointTaskItemId,
        String        orgId,
        String        pointId,
        Boolean       required,
        LocalDateTime createdDate,
        String        creator,
        LocalDateTime updateDate,
        String        modifier
    ) {
        this.id = id;
        this.pointTaskItemId = pointTaskItemId;
        this.orgId = orgId;
        this.pointId = pointId;
        this.required = required;
        this.createdDate = createdDate;
        this.creator = creator;
        this.updateDate = updateDate;
        this.modifier = modifier;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPointTaskItemId() {
        return this.pointTaskItemId;
    }

    public void setPointTaskItemId(String pointTaskItemId) {
        this.pointTaskItemId = pointTaskItemId;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getPointId() {
        return this.pointId;
    }

    public void setPointId(String pointId) {
        this.pointId = pointId;
    }

    public Boolean getRequired() {
        return this.required;
    }

    public void setRequired(Boolean required) {
        this.required = required;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BizPointTaskItemPoint (");

        sb.append(id);
        sb.append(", ").append(pointTaskItemId);
        sb.append(", ").append(orgId);
        sb.append(", ").append(pointId);
        sb.append(", ").append(required);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(creator);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(modifier);

        sb.append(")");
        return sb.toString();
    }
}
