/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizUserOnlineTime implements Serializable {

    private static final long serialVersionUID = -639925886;

    private String        id;
    private String        userId;
    private String        userName;
    private String        orgId;
    private Integer       onlineSecond;
    private LocalDateTime recordDate;
    private LocalDateTime createTime;

    public BizUserOnlineTime() {}

    public BizUserOnlineTime(BizUserOnlineTime value) {
        this.id = value.id;
        this.userId = value.userId;
        this.userName = value.userName;
        this.orgId = value.orgId;
        this.onlineSecond = value.onlineSecond;
        this.recordDate = value.recordDate;
        this.createTime = value.createTime;
    }

    public BizUserOnlineTime(
        String        id,
        String        userId,
        String        userName,
        String        orgId,
        Integer       onlineSecond,
        LocalDateTime recordDate,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.orgId = orgId;
        this.onlineSecond = onlineSecond;
        this.recordDate = recordDate;
        this.createTime = createTime;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public Integer getOnlineSecond() {
        return this.onlineSecond;
    }

    public void setOnlineSecond(Integer onlineSecond) {
        this.onlineSecond = onlineSecond;
    }

    public LocalDateTime getRecordDate() {
        return this.recordDate;
    }

    public void setRecordDate(LocalDateTime recordDate) {
        this.recordDate = recordDate;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BizUserOnlineTime (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(orgId);
        sb.append(", ").append(onlineSecond);
        sb.append(", ").append(recordDate);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
