/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables;


import com.mr.sa.generator.Indexes;
import com.mr.sa.generator.Keys;
import com.mr.sa.generator.Sa;
import com.mr.sa.generator.tables.records.BizPointTaskItemPointRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 关系:巡防任务/巡防组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointTaskItemPoint extends TableImpl<BizPointTaskItemPointRecord> {

    private static final long serialVersionUID = -372344159;

    /**
     * The reference instance of <code>sa.biz_point_task_item_point</code>
     */
    public static final BizPointTaskItemPoint BIZ_POINT_TASK_ITEM_POINT = new BizPointTaskItemPoint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizPointTaskItemPointRecord> getRecordType() {
        return BizPointTaskItemPointRecord.class;
    }

    /**
     * The column <code>sa.biz_point_task_item_point.id</code>.
     */
    public final TableField<BizPointTaskItemPointRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>sa.biz_point_task_item_point.point_task_item_id</code>. 巡防任务ID
     */
    public final TableField<BizPointTaskItemPointRecord, String> POINT_TASK_ITEM_ID = createField("point_task_item_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "巡防任务ID");

    /**
     * The column <code>sa.biz_point_task_item_point.org_id</code>.
     */
    public final TableField<BizPointTaskItemPointRecord, String> ORG_ID = createField("org_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>sa.biz_point_task_item_point.point_id</code>. 巡防点ID
     */
    public final TableField<BizPointTaskItemPointRecord, String> POINT_ID = createField("point_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "巡防点ID");

    /**
     * The column <code>sa.biz_point_task_item_point.required</code>. 是否为必扫点
     */
    public final TableField<BizPointTaskItemPointRecord, Boolean> REQUIRED = createField("required", org.jooq.impl.SQLDataType.BIT, this, "是否为必扫点");

    /**
     * The column <code>sa.biz_point_task_item_point.created_date</code>. 创建日期
     */
    public final TableField<BizPointTaskItemPointRecord, LocalDateTime> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "创建日期");

    /**
     * The column <code>sa.biz_point_task_item_point.creator</code>. 创建人
     */
    public final TableField<BizPointTaskItemPointRecord, String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.VARCHAR(32), this, "创建人");

    /**
     * The column <code>sa.biz_point_task_item_point.update_date</code>. 修改日期
     */
    public final TableField<BizPointTaskItemPointRecord, LocalDateTime> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "修改日期");

    /**
     * The column <code>sa.biz_point_task_item_point.modifier</code>. 修改人
     */
    public final TableField<BizPointTaskItemPointRecord, String> MODIFIER = createField("modifier", org.jooq.impl.SQLDataType.VARCHAR(32), this, "修改人");

    /**
     * Create a <code>sa.biz_point_task_item_point</code> table reference
     */
    public BizPointTaskItemPoint() {
        this(DSL.name("biz_point_task_item_point"), null);
    }

    /**
     * Create an aliased <code>sa.biz_point_task_item_point</code> table reference
     */
    public BizPointTaskItemPoint(String alias) {
        this(DSL.name(alias), BIZ_POINT_TASK_ITEM_POINT);
    }

    /**
     * Create an aliased <code>sa.biz_point_task_item_point</code> table reference
     */
    public BizPointTaskItemPoint(Name alias) {
        this(alias, BIZ_POINT_TASK_ITEM_POINT);
    }

    private BizPointTaskItemPoint(Name alias, Table<BizPointTaskItemPointRecord> aliased) {
        this(alias, aliased, null);
    }

    private BizPointTaskItemPoint(Name alias, Table<BizPointTaskItemPointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "关系:巡防任务/巡防组织");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sa.SA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BIZ_POINT_TASK_ITEM_POINT_ORG_ID, Indexes.BIZ_POINT_TASK_ITEM_POINT_PATROL_POINT_ID, Indexes.BIZ_POINT_TASK_ITEM_POINT_PATROL_TASK_ITEM_ID, Indexes.BIZ_POINT_TASK_ITEM_POINT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BizPointTaskItemPointRecord> getPrimaryKey() {
        return Keys.KEY_BIZ_POINT_TASK_ITEM_POINT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BizPointTaskItemPointRecord>> getKeys() {
        return Arrays.<UniqueKey<BizPointTaskItemPointRecord>>asList(Keys.KEY_BIZ_POINT_TASK_ITEM_POINT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPoint as(String alias) {
        return new BizPointTaskItemPoint(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointTaskItemPoint as(Name alias) {
        return new BizPointTaskItemPoint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizPointTaskItemPoint rename(String name) {
        return new BizPointTaskItemPoint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizPointTaskItemPoint rename(Name name) {
        return new BizPointTaskItemPoint(name, null);
    }
}
