/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables;


import com.mr.sa.generator.Indexes;
import com.mr.sa.generator.Keys;
import com.mr.sa.generator.Sa;
import com.mr.sa.generator.tables.records.BizPatrolPointRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 巡防点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPatrolPoint extends TableImpl<BizPatrolPointRecord> {

    private static final long serialVersionUID = 203015720;

    /**
     * The reference instance of <code>sa.biz_patrol_point</code>
     */
    public static final BizPatrolPoint BIZ_PATROL_POINT = new BizPatrolPoint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizPatrolPointRecord> getRecordType() {
        return BizPatrolPointRecord.class;
    }

    /**
     * The column <code>sa.biz_patrol_point.id</code>.
     */
    public final TableField<BizPatrolPointRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>sa.biz_patrol_point.code</code>. 编码
     */
    public final TableField<BizPatrolPointRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(32), this, "编码");

    /**
     * The column <code>sa.biz_patrol_point.name</code>. 名称
     */
    public final TableField<BizPatrolPointRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "名称");

    /**
     * The column <code>sa.biz_patrol_point.longitude</code>. 经度
     */
    public final TableField<BizPatrolPointRecord, String> LONGITUDE = createField("longitude", org.jooq.impl.SQLDataType.VARCHAR(32), this, "经度");

    /**
     * The column <code>sa.biz_patrol_point.latitude</code>. 纬度
     */
    public final TableField<BizPatrolPointRecord, String> LATITUDE = createField("latitude", org.jooq.impl.SQLDataType.VARCHAR(32), this, "纬度");

    /**
     * The column <code>sa.biz_patrol_point.qrcode_url</code>.
     */
    public final TableField<BizPatrolPointRecord, String> QRCODE_URL = createField("qrcode_url", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>sa.biz_patrol_point.qr_code</code>. 二维码编码
     */
    public final TableField<BizPatrolPointRecord, String> QR_CODE = createField("qr_code", org.jooq.impl.SQLDataType.VARCHAR(32), this, "二维码编码");

    /**
     * The column <code>sa.biz_patrol_point.created_date</code>. 创建日期
     */
    public final TableField<BizPatrolPointRecord, LocalDateTime> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "创建日期");

    /**
     * The column <code>sa.biz_patrol_point.creator</code>. 创建人
     */
    public final TableField<BizPatrolPointRecord, String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.VARCHAR(32), this, "创建人");

    /**
     * The column <code>sa.biz_patrol_point.update_date</code>. 修改日期
     */
    public final TableField<BizPatrolPointRecord, LocalDateTime> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "修改日期");

    /**
     * The column <code>sa.biz_patrol_point.modifier</code>. 修改人
     */
    public final TableField<BizPatrolPointRecord, String> MODIFIER = createField("modifier", org.jooq.impl.SQLDataType.VARCHAR(32), this, "修改人");

    /**
     * The column <code>sa.biz_patrol_point.org_id</code>.
     */
    public final TableField<BizPatrolPointRecord, String> ORG_ID = createField("org_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>sa.biz_patrol_point.level</code>. 1:1级巡防点, 2:2级巡防点
     */
    public final TableField<BizPatrolPointRecord, String> LEVEL = createField("level", org.jooq.impl.SQLDataType.VARCHAR(16), this, "1:1级巡防点, 2:2级巡防点");

    /**
     * The column <code>sa.biz_patrol_point.type</code>. 扫码点: scan_point，立岗点: sentry_point，盘查点: inspect_point
     */
    public final TableField<BizPatrolPointRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(64), this, "扫码点: scan_point，立岗点: sentry_point，盘查点: inspect_point");

    /**
     * Create a <code>sa.biz_patrol_point</code> table reference
     */
    public BizPatrolPoint() {
        this(DSL.name("biz_patrol_point"), null);
    }

    /**
     * Create an aliased <code>sa.biz_patrol_point</code> table reference
     */
    public BizPatrolPoint(String alias) {
        this(DSL.name(alias), BIZ_PATROL_POINT);
    }

    /**
     * Create an aliased <code>sa.biz_patrol_point</code> table reference
     */
    public BizPatrolPoint(Name alias) {
        this(alias, BIZ_PATROL_POINT);
    }

    private BizPatrolPoint(Name alias, Table<BizPatrolPointRecord> aliased) {
        this(alias, aliased, null);
    }

    private BizPatrolPoint(Name alias, Table<BizPatrolPointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "巡防点");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sa.SA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BIZ_PATROL_POINT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BizPatrolPointRecord> getPrimaryKey() {
        return Keys.KEY_BIZ_PATROL_POINT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BizPatrolPointRecord>> getKeys() {
        return Arrays.<UniqueKey<BizPatrolPointRecord>>asList(Keys.KEY_BIZ_PATROL_POINT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPoint as(String alias) {
        return new BizPatrolPoint(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPatrolPoint as(Name alias) {
        return new BizPatrolPoint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizPatrolPoint rename(String name) {
        return new BizPatrolPoint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizPatrolPoint rename(Name name) {
        return new BizPatrolPoint(name, null);
    }
}
