/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables;


import com.mr.sa.generator.Indexes;
import com.mr.sa.generator.Keys;
import com.mr.sa.generator.Sa;
import com.mr.sa.generator.tables.records.BizPointPlanRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 巡防活动
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointPlan extends TableImpl<BizPointPlanRecord> {

    private static final long serialVersionUID = 1327470393;

    /**
     * The reference instance of <code>sa.biz_point_plan</code>
     */
    public static final BizPointPlan BIZ_POINT_PLAN = new BizPointPlan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizPointPlanRecord> getRecordType() {
        return BizPointPlanRecord.class;
    }

    /**
     * The column <code>sa.biz_point_plan.id</code>.
     */
    public final TableField<BizPointPlanRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>sa.biz_point_plan.name</code>. 计划名称
     */
    public final TableField<BizPointPlanRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "计划名称");

    /**
     * The column <code>sa.biz_point_plan.org_id</code>. 组织ID
     */
    public final TableField<BizPointPlanRecord, String> ORG_ID = createField("org_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "组织ID");

    /**
     * The column <code>sa.biz_point_plan.announce_time</code>. 下发时间
     */
    public final TableField<BizPointPlanRecord, LocalDate> ANNOUNCE_TIME = createField("announce_time", org.jooq.impl.SQLDataType.LOCALDATE, this, "下发时间");

    /**
     * The column <code>sa.biz_point_plan.patrol_start_time</code>. 巡防开始时间
     */
    public final TableField<BizPointPlanRecord, LocalDateTime> PATROL_START_TIME = createField("patrol_start_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "巡防开始时间");

    /**
     * The column <code>sa.biz_point_plan.patrol_end_time</code>. 巡防结束时间
     */
    public final TableField<BizPointPlanRecord, LocalDateTime> PATROL_END_TIME = createField("patrol_end_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "巡防结束时间");

    /**
     * The column <code>sa.biz_point_plan.done_ratio</code>. 规定完成比例
     */
    public final TableField<BizPointPlanRecord, Integer> DONE_RATIO = createField("done_ratio", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "规定完成比例");

    /**
     * The column <code>sa.biz_point_plan.work_status</code>. 完成状态
     */
    public final TableField<BizPointPlanRecord, String> WORK_STATUS = createField("work_status", org.jooq.impl.SQLDataType.VARCHAR(16), this, "完成状态");

    /**
     * The column <code>sa.biz_point_plan.reason</code>. 原因
     */
    public final TableField<BizPointPlanRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "原因");

    /**
     * The column <code>sa.biz_point_plan.point_task_item_id</code>. 点子任务ID
     */
    public final TableField<BizPointPlanRecord, String> POINT_TASK_ITEM_ID = createField("point_task_item_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "点子任务ID");

    /**
     * The column <code>sa.biz_point_plan.point_task_id</code>. 点任务ID
     */
    public final TableField<BizPointPlanRecord, String> POINT_TASK_ID = createField("point_task_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "点任务ID");

    /**
     * The column <code>sa.biz_point_plan.time_interval</code>. 时间间隔(分钟）
     */
    public final TableField<BizPointPlanRecord, Integer> TIME_INTERVAL = createField("time_interval", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("60", org.jooq.impl.SQLDataType.INTEGER)), this, "时间间隔(分钟）");

    /**
     * The column <code>sa.biz_point_plan.time_redundancy</code>. 时间误差(分钟)
     */
    public final TableField<BizPointPlanRecord, Integer> TIME_REDUNDANCY = createField("time_redundancy", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("5", org.jooq.impl.SQLDataType.INTEGER)), this, "时间误差(分钟)");

    /**
     * The column <code>sa.biz_point_plan.member_amount</code>. 巡防人员数量
     */
    public final TableField<BizPointPlanRecord, Integer> MEMBER_AMOUNT = createField("member_amount", org.jooq.impl.SQLDataType.INTEGER, this, "巡防人员数量");

    /**
     * The column <code>sa.biz_point_plan.cop_amount</code>. 巡防民警数量
     */
    public final TableField<BizPointPlanRecord, Integer> COP_AMOUNT = createField("cop_amount", org.jooq.impl.SQLDataType.INTEGER, this, "巡防民警数量");

    /**
     * The column <code>sa.biz_point_plan.ap_amount</code>. 巡防辅警人员数量
     */
    public final TableField<BizPointPlanRecord, Integer> AP_AMOUNT = createField("ap_amount", org.jooq.impl.SQLDataType.INTEGER, this, "巡防辅警人员数量");

    /**
     * The column <code>sa.biz_point_plan.created_date</code>. 创建日期
     */
    public final TableField<BizPointPlanRecord, LocalDateTime> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "创建日期");

    /**
     * The column <code>sa.biz_point_plan.creator</code>. 创建人
     */
    public final TableField<BizPointPlanRecord, String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.VARCHAR(32), this, "创建人");

    /**
     * The column <code>sa.biz_point_plan.update_date</code>. 修改日期
     */
    public final TableField<BizPointPlanRecord, LocalDateTime> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "修改日期");

    /**
     * The column <code>sa.biz_point_plan.modifier</code>. 修改人
     */
    public final TableField<BizPointPlanRecord, String> MODIFIER = createField("modifier", org.jooq.impl.SQLDataType.VARCHAR(32), this, "修改人");

    /**
     * Create a <code>sa.biz_point_plan</code> table reference
     */
    public BizPointPlan() {
        this(DSL.name("biz_point_plan"), null);
    }

    /**
     * Create an aliased <code>sa.biz_point_plan</code> table reference
     */
    public BizPointPlan(String alias) {
        this(DSL.name(alias), BIZ_POINT_PLAN);
    }

    /**
     * Create an aliased <code>sa.biz_point_plan</code> table reference
     */
    public BizPointPlan(Name alias) {
        this(alias, BIZ_POINT_PLAN);
    }

    private BizPointPlan(Name alias, Table<BizPointPlanRecord> aliased) {
        this(alias, aliased, null);
    }

    private BizPointPlan(Name alias, Table<BizPointPlanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "巡防活动");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sa.SA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BIZ_POINT_PLAN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BizPointPlanRecord> getPrimaryKey() {
        return Keys.KEY_BIZ_POINT_PLAN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BizPointPlanRecord>> getKeys() {
        return Arrays.<UniqueKey<BizPointPlanRecord>>asList(Keys.KEY_BIZ_POINT_PLAN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointPlan as(String alias) {
        return new BizPointPlan(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizPointPlan as(Name alias) {
        return new BizPointPlan(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizPointPlan rename(String name) {
        return new BizPointPlan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizPointPlan rename(Name name) {
        return new BizPointPlan(name, null);
    }
}
