/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables;


import com.mr.sa.generator.Indexes;
import com.mr.sa.generator.Keys;
import com.mr.sa.generator.Sa;
import com.mr.sa.generator.tables.records.BizUserOnlineTimeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizUserOnlineTime extends TableImpl<BizUserOnlineTimeRecord> {

    private static final long serialVersionUID = 1009998243;

    /**
     * The reference instance of <code>sa.biz_user_online_time</code>
     */
    public static final BizUserOnlineTime BIZ_USER_ONLINE_TIME = new BizUserOnlineTime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizUserOnlineTimeRecord> getRecordType() {
        return BizUserOnlineTimeRecord.class;
    }

    /**
     * The column <code>sa.biz_user_online_time.id</code>.
     */
    public final TableField<BizUserOnlineTimeRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>sa.biz_user_online_time.user_id</code>. 用户id
     */
    public final TableField<BizUserOnlineTimeRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "用户id");

    /**
     * The column <code>sa.biz_user_online_time.user_name</code>. 用户名称
     */
    public final TableField<BizUserOnlineTimeRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR(32), this, "用户名称");

    /**
     * The column <code>sa.biz_user_online_time.org_id</code>. 单位id
     */
    public final TableField<BizUserOnlineTimeRecord, String> ORG_ID = createField("org_id", org.jooq.impl.SQLDataType.VARCHAR(32), this, "单位id");

    /**
     * The column <code>sa.biz_user_online_time.online_second</code>. 在线巡逻时长
     */
    public final TableField<BizUserOnlineTimeRecord, Integer> ONLINE_SECOND = createField("online_second", org.jooq.impl.SQLDataType.INTEGER, this, "在线巡逻时长");

    /**
     * The column <code>sa.biz_user_online_time.record_date</code>. 记录日期
     */
    public final TableField<BizUserOnlineTimeRecord, LocalDateTime> RECORD_DATE = createField("record_date", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "记录日期");

    /**
     * The column <code>sa.biz_user_online_time.create_time</code>. 创建时间
     */
    public final TableField<BizUserOnlineTimeRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "创建时间");

    /**
     * Create a <code>sa.biz_user_online_time</code> table reference
     */
    public BizUserOnlineTime() {
        this(DSL.name("biz_user_online_time"), null);
    }

    /**
     * Create an aliased <code>sa.biz_user_online_time</code> table reference
     */
    public BizUserOnlineTime(String alias) {
        this(DSL.name(alias), BIZ_USER_ONLINE_TIME);
    }

    /**
     * Create an aliased <code>sa.biz_user_online_time</code> table reference
     */
    public BizUserOnlineTime(Name alias) {
        this(alias, BIZ_USER_ONLINE_TIME);
    }

    private BizUserOnlineTime(Name alias, Table<BizUserOnlineTimeRecord> aliased) {
        this(alias, aliased, null);
    }

    private BizUserOnlineTime(Name alias, Table<BizUserOnlineTimeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sa.SA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BIZ_USER_ONLINE_TIME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BizUserOnlineTimeRecord> getPrimaryKey() {
        return Keys.KEY_BIZ_USER_ONLINE_TIME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BizUserOnlineTimeRecord>> getKeys() {
        return Arrays.<UniqueKey<BizUserOnlineTimeRecord>>asList(Keys.KEY_BIZ_USER_ONLINE_TIME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserOnlineTime as(String alias) {
        return new BizUserOnlineTime(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BizUserOnlineTime as(Name alias) {
        return new BizUserOnlineTime(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizUserOnlineTime rename(String name) {
        return new BizUserOnlineTime(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizUserOnlineTime rename(Name name) {
        return new BizUserOnlineTime(name, null);
    }
}
