/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizAppUser;
import com.mr.sa.generator.tables.records.BizAppUserRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizAppUserDao extends DAOImpl<BizAppUserRecord, com.mr.sa.generator.tables.pojos.BizAppUser, String> {

    /**
     * Create a new BizAppUserDao without any configuration
     */
    public BizAppUserDao() {
        super(BizAppUser.BIZ_APP_USER, com.mr.sa.generator.tables.pojos.BizAppUser.class);
    }

    /**
     * Create a new BizAppUserDao with an attached configuration
     */
    public BizAppUserDao(Configuration configuration) {
        super(BizAppUser.BIZ_APP_USER, com.mr.sa.generator.tables.pojos.BizAppUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizAppUser object) {
        return object.getId_();
    }

    /**
     * Fetch records that have <code>id_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchById_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.ID_, values);
    }

    /**
     * Fetch a unique record that has <code>id_ = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizAppUser fetchOneById_(String value) {
        return fetchOne(BizAppUser.BIZ_APP_USER.ID_, value);
    }

    /**
     * Fetch records that have <code>role_Id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByRoleId(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>username_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByUsername_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.USERNAME_, values);
    }

    /**
     * Fetch a unique record that has <code>username_ = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizAppUser fetchOneByUsername_(String value) {
        return fetchOne(BizAppUser.BIZ_APP_USER.USERNAME_, value);
    }

    /**
     * Fetch records that have <code>enabled_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByEnabled_(Boolean... values) {
        return fetch(BizAppUser.BIZ_APP_USER.ENABLED_, values);
    }

    /**
     * Fetch records that have <code>nickname_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByNickname_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.NICKNAME_, values);
    }

    /**
     * Fetch records that have <code>password_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByPassword_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.PASSWORD_, values);
    }

    /**
     * Fetch records that have <code>org_id_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByOrgId_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.ORG_ID_, values);
    }

    /**
     * Fetch records that have <code>gender_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByGender_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.GENDER_, values);
    }

    /**
     * Fetch records that have <code>phone_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByPhone_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.PHONE_, values);
    }

    /**
     * Fetch records that have <code>mail_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByMail_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.MAIL_, values);
    }

    /**
     * Fetch records that have <code>address_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByAddress_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.ADDRESS_, values);
    }

    /**
     * Fetch records that have <code>remark_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByRemark_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.REMARK_, values);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(BizAppUser.BIZ_APP_USER.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByCreator(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.CREATOR, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(BizAppUser.BIZ_APP_USER.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByModifier(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>avatar_ IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizAppUser> fetchByAvatar_(String... values) {
        return fetch(BizAppUser.BIZ_APP_USER.AVATAR_, values);
    }
}
