/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizOrg;
import com.mr.sa.generator.tables.records.BizOrgRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizOrgDao extends DAOImpl<BizOrgRecord, com.mr.sa.generator.tables.pojos.BizOrg, String> {

    /**
     * Create a new BizOrgDao without any configuration
     */
    public BizOrgDao() {
        super(BizOrg.BIZ_ORG, com.mr.sa.generator.tables.pojos.BizOrg.class);
    }

    /**
     * Create a new BizOrgDao with an attached configuration
     */
    public BizOrgDao(Configuration configuration) {
        super(BizOrg.BIZ_ORG, com.mr.sa.generator.tables.pojos.BizOrg.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizOrg object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchById(String... values) {
        return fetch(BizOrg.BIZ_ORG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizOrg fetchOneById(String value) {
        return fetchOne(BizOrg.BIZ_ORG.ID, value);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByCode(String... values) {
        return fetch(BizOrg.BIZ_ORG.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>code = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizOrg fetchOneByCode(String value) {
        return fetchOne(BizOrg.BIZ_ORG.CODE, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByName(String... values) {
        return fetch(BizOrg.BIZ_ORG.NAME, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByParentId(String... values) {
        return fetch(BizOrg.BIZ_ORG.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByLongitude(String... values) {
        return fetch(BizOrg.BIZ_ORG.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByLatitude(String... values) {
        return fetch(BizOrg.BIZ_ORG.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByAddress(String... values) {
        return fetch(BizOrg.BIZ_ORG.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(BizOrg.BIZ_ORG.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(BizOrg.BIZ_ORG.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByCreator(String... values) {
        return fetch(BizOrg.BIZ_ORG.CREATOR, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByModifier(String... values) {
        return fetch(BizOrg.BIZ_ORG.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>telephone IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizOrg> fetchByTelephone(String... values) {
        return fetch(BizOrg.BIZ_ORG.TELEPHONE, values);
    }
}
