/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizPointTaskItemPoint;
import com.mr.sa.generator.tables.records.BizPointTaskItemPointRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 关系:巡防任务/巡防组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointTaskItemPointDao extends DAOImpl<BizPointTaskItemPointRecord, com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint, String> {

    /**
     * Create a new BizPointTaskItemPointDao without any configuration
     */
    public BizPointTaskItemPointDao() {
        super(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT, com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint.class);
    }

    /**
     * Create a new BizPointTaskItemPointDao with an attached configuration
     */
    public BizPointTaskItemPointDao(Configuration configuration) {
        super(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT, com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchById(String... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint fetchOneById(String value) {
        return fetchOne(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ID, value);
    }

    /**
     * Fetch records that have <code>point_task_item_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByPointTaskItemId(String... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.POINT_TASK_ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>org_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByOrgId(String... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ORG_ID, values);
    }

    /**
     * Fetch records that have <code>point_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByPointId(String... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.POINT_ID, values);
    }

    /**
     * Fetch records that have <code>required IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByRequired(Boolean... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.REQUIRED, values);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByCreator(String... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.CREATOR, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemPoint> fetchByModifier(String... values) {
        return fetch(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.MODIFIER, values);
    }
}
