/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizPointTaskItemOrg;
import com.mr.sa.generator.tables.records.BizPointTaskItemOrgRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 关系:巡防任务/巡防组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointTaskItemOrgDao extends DAOImpl<BizPointTaskItemOrgRecord, com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg, String> {

    /**
     * Create a new BizPointTaskItemOrgDao without any configuration
     */
    public BizPointTaskItemOrgDao() {
        super(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG, com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg.class);
    }

    /**
     * Create a new BizPointTaskItemOrgDao with an attached configuration
     */
    public BizPointTaskItemOrgDao(Configuration configuration) {
        super(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG, com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg> fetchById(String... values) {
        return fetch(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg fetchOneById(String value) {
        return fetchOne(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.ID, value);
    }

    /**
     * Fetch records that have <code>point_task_item_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg> fetchByPointTaskItemId(String... values) {
        return fetch(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.POINT_TASK_ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>org_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg> fetchByOrgId(String... values) {
        return fetch(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.ORG_ID, values);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg> fetchByCreator(String... values) {
        return fetch(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.CREATOR, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointTaskItemOrg> fetchByModifier(String... values) {
        return fetch(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.MODIFIER, values);
    }
}
