/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizPatrolPoint;
import com.mr.sa.generator.tables.records.BizPatrolPointRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 巡防点
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPatrolPointDao extends DAOImpl<BizPatrolPointRecord, com.mr.sa.generator.tables.pojos.BizPatrolPoint, String> {

    /**
     * Create a new BizPatrolPointDao without any configuration
     */
    public BizPatrolPointDao() {
        super(BizPatrolPoint.BIZ_PATROL_POINT, com.mr.sa.generator.tables.pojos.BizPatrolPoint.class);
    }

    /**
     * Create a new BizPatrolPointDao with an attached configuration
     */
    public BizPatrolPointDao(Configuration configuration) {
        super(BizPatrolPoint.BIZ_PATROL_POINT, com.mr.sa.generator.tables.pojos.BizPatrolPoint.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizPatrolPoint object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchById(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizPatrolPoint fetchOneById(String value) {
        return fetchOne(BizPatrolPoint.BIZ_PATROL_POINT.ID, value);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByCode(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.CODE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByName(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.NAME, values);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByLongitude(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByLatitude(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>qrcode_url IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByQrcodeUrl(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.QRCODE_URL, values);
    }

    /**
     * Fetch records that have <code>qr_code IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByQrCode(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.QR_CODE, values);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByCreator(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.CREATOR, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByModifier(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>org_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByOrgId(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.ORG_ID, values);
    }

    /**
     * Fetch records that have <code>level IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByLevel(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.LEVEL, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPatrolPoint> fetchByType(String... values) {
        return fetch(BizPatrolPoint.BIZ_PATROL_POINT.TYPE, values);
    }
}
