/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizPointPlan;
import com.mr.sa.generator.tables.records.BizPointPlanRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 巡防活动
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizPointPlanDao extends DAOImpl<BizPointPlanRecord, com.mr.sa.generator.tables.pojos.BizPointPlan, String> {

    /**
     * Create a new BizPointPlanDao without any configuration
     */
    public BizPointPlanDao() {
        super(BizPointPlan.BIZ_POINT_PLAN, com.mr.sa.generator.tables.pojos.BizPointPlan.class);
    }

    /**
     * Create a new BizPointPlanDao with an attached configuration
     */
    public BizPointPlanDao(Configuration configuration) {
        super(BizPointPlan.BIZ_POINT_PLAN, com.mr.sa.generator.tables.pojos.BizPointPlan.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizPointPlan object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchById(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizPointPlan fetchOneById(String value) {
        return fetchOne(BizPointPlan.BIZ_POINT_PLAN.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByName(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.NAME, values);
    }

    /**
     * Fetch records that have <code>org_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByOrgId(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.ORG_ID, values);
    }

    /**
     * Fetch records that have <code>announce_time IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByAnnounceTime(LocalDate... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.ANNOUNCE_TIME, values);
    }

    /**
     * Fetch records that have <code>patrol_start_time IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByPatrolStartTime(LocalDateTime... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.PATROL_START_TIME, values);
    }

    /**
     * Fetch records that have <code>patrol_end_time IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByPatrolEndTime(LocalDateTime... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.PATROL_END_TIME, values);
    }

    /**
     * Fetch records that have <code>done_ratio IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByDoneRatio(Integer... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.DONE_RATIO, values);
    }

    /**
     * Fetch records that have <code>work_status IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByWorkStatus(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.WORK_STATUS, values);
    }

    /**
     * Fetch records that have <code>reason IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByReason(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.REASON, values);
    }

    /**
     * Fetch records that have <code>point_task_item_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByPointTaskItemId(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.POINT_TASK_ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>point_task_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByPointTaskId(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.POINT_TASK_ID, values);
    }

    /**
     * Fetch records that have <code>time_interval IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByTimeInterval(Integer... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.TIME_INTERVAL, values);
    }

    /**
     * Fetch records that have <code>time_redundancy IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByTimeRedundancy(Integer... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.TIME_REDUNDANCY, values);
    }

    /**
     * Fetch records that have <code>member_amount IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByMemberAmount(Integer... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.MEMBER_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>cop_amount IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByCopAmount(Integer... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.COP_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>ap_amount IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByApAmount(Integer... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.AP_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByCreator(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.CREATOR, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizPointPlan> fetchByModifier(String... values) {
        return fetch(BizPointPlan.BIZ_POINT_PLAN.MODIFIER, values);
    }
}
