/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizUserOnlineTime;
import com.mr.sa.generator.tables.records.BizUserOnlineTimeRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizUserOnlineTimeDao extends DAOImpl<BizUserOnlineTimeRecord, com.mr.sa.generator.tables.pojos.BizUserOnlineTime, String> {

    /**
     * Create a new BizUserOnlineTimeDao without any configuration
     */
    public BizUserOnlineTimeDao() {
        super(BizUserOnlineTime.BIZ_USER_ONLINE_TIME, com.mr.sa.generator.tables.pojos.BizUserOnlineTime.class);
    }

    /**
     * Create a new BizUserOnlineTimeDao with an attached configuration
     */
    public BizUserOnlineTimeDao(Configuration configuration) {
        super(BizUserOnlineTime.BIZ_USER_ONLINE_TIME, com.mr.sa.generator.tables.pojos.BizUserOnlineTime.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizUserOnlineTime object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserOnlineTime> fetchById(String... values) {
        return fetch(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizUserOnlineTime fetchOneById(String value) {
        return fetchOne(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserOnlineTime> fetchByUserId(String... values) {
        return fetch(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.USER_ID, values);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserOnlineTime> fetchByUserName(String... values) {
        return fetch(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>org_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserOnlineTime> fetchByOrgId(String... values) {
        return fetch(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.ORG_ID, values);
    }

    /**
     * Fetch records that have <code>online_second IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserOnlineTime> fetchByOnlineSecond(Integer... values) {
        return fetch(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.ONLINE_SECOND, values);
    }

    /**
     * Fetch records that have <code>record_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserOnlineTime> fetchByRecordDate(LocalDateTime... values) {
        return fetch(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.RECORD_DATE, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserOnlineTime> fetchByCreateTime(LocalDateTime... values) {
        return fetch(BizUserOnlineTime.BIZ_USER_ONLINE_TIME.CREATE_TIME, values);
    }
}
