/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator.tables.daos;


import com.mr.sa.generator.tables.BizUserKeepOnlineTime;
import com.mr.sa.generator.tables.records.BizUserKeepOnlineTimeRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BizUserKeepOnlineTimeDao extends DAOImpl<BizUserKeepOnlineTimeRecord, com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime, String> {

    /**
     * Create a new BizUserKeepOnlineTimeDao without any configuration
     */
    public BizUserKeepOnlineTimeDao() {
        super(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME, com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime.class);
    }

    /**
     * Create a new BizUserKeepOnlineTimeDao with an attached configuration
     */
    public BizUserKeepOnlineTimeDao(Configuration configuration) {
        super(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME, com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime> fetchById(String... values) {
        return fetch(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime fetchOneById(String value) {
        return fetchOne(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime> fetchByUserId(String... values) {
        return fetch(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.USER_ID, values);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime> fetchByUserName(String... values) {
        return fetch(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>org_id IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime> fetchByOrgId(String... values) {
        return fetch(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ORG_ID, values);
    }

    /**
     * Fetch records that have <code>online_second IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime> fetchByOnlineSecond(Integer... values) {
        return fetch(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ONLINE_SECOND, values);
    }

    /**
     * Fetch records that have <code>record_date IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime> fetchByRecordDate(LocalDateTime... values) {
        return fetch(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.RECORD_DATE, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.mr.sa.generator.tables.pojos.BizUserKeepOnlineTime> fetchByCreateTime(LocalDateTime... values) {
        return fetch(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.CREATE_TIME, values);
    }
}
