/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator;


import com.mr.sa.generator.tables.BizAppUser;
import com.mr.sa.generator.tables.BizOrg;
import com.mr.sa.generator.tables.BizPatrolPoint;
import com.mr.sa.generator.tables.BizPointPlan;
import com.mr.sa.generator.tables.BizPointTaskItemOrg;
import com.mr.sa.generator.tables.BizPointTaskItemPoint;
import com.mr.sa.generator.tables.BizUserKeepOnlineTime;
import com.mr.sa.generator.tables.BizUserOnlineTime;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>sa</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BIZ_APP_USER_PRIMARY = Indexes0.BIZ_APP_USER_PRIMARY;
    public static final Index BIZ_APP_USER_USERNAME_ = Indexes0.BIZ_APP_USER_USERNAME_;
    public static final Index BIZ_ORG_CODE = Indexes0.BIZ_ORG_CODE;
    public static final Index BIZ_ORG_PRIMARY = Indexes0.BIZ_ORG_PRIMARY;
    public static final Index BIZ_PATROL_POINT_PRIMARY = Indexes0.BIZ_PATROL_POINT_PRIMARY;
    public static final Index BIZ_POINT_PLAN_PRIMARY = Indexes0.BIZ_POINT_PLAN_PRIMARY;
    public static final Index BIZ_POINT_TASK_ITEM_ORG_PRIMARY = Indexes0.BIZ_POINT_TASK_ITEM_ORG_PRIMARY;
    public static final Index BIZ_POINT_TASK_ITEM_POINT_ORG_ID = Indexes0.BIZ_POINT_TASK_ITEM_POINT_ORG_ID;
    public static final Index BIZ_POINT_TASK_ITEM_POINT_PATROL_POINT_ID = Indexes0.BIZ_POINT_TASK_ITEM_POINT_PATROL_POINT_ID;
    public static final Index BIZ_POINT_TASK_ITEM_POINT_PATROL_TASK_ITEM_ID = Indexes0.BIZ_POINT_TASK_ITEM_POINT_PATROL_TASK_ITEM_ID;
    public static final Index BIZ_POINT_TASK_ITEM_POINT_PRIMARY = Indexes0.BIZ_POINT_TASK_ITEM_POINT_PRIMARY;
    public static final Index BIZ_USER_KEEP_ONLINE_TIME_PRIMARY = Indexes0.BIZ_USER_KEEP_ONLINE_TIME_PRIMARY;
    public static final Index BIZ_USER_ONLINE_TIME_PRIMARY = Indexes0.BIZ_USER_ONLINE_TIME_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BIZ_APP_USER_PRIMARY = Internal.createIndex("PRIMARY", BizAppUser.BIZ_APP_USER, new OrderField[] { BizAppUser.BIZ_APP_USER.ID_ }, true);
        public static Index BIZ_APP_USER_USERNAME_ = Internal.createIndex("username_", BizAppUser.BIZ_APP_USER, new OrderField[] { BizAppUser.BIZ_APP_USER.USERNAME_ }, true);
        public static Index BIZ_ORG_CODE = Internal.createIndex("code", BizOrg.BIZ_ORG, new OrderField[] { BizOrg.BIZ_ORG.CODE }, true);
        public static Index BIZ_ORG_PRIMARY = Internal.createIndex("PRIMARY", BizOrg.BIZ_ORG, new OrderField[] { BizOrg.BIZ_ORG.ID }, true);
        public static Index BIZ_PATROL_POINT_PRIMARY = Internal.createIndex("PRIMARY", BizPatrolPoint.BIZ_PATROL_POINT, new OrderField[] { BizPatrolPoint.BIZ_PATROL_POINT.ID }, true);
        public static Index BIZ_POINT_PLAN_PRIMARY = Internal.createIndex("PRIMARY", BizPointPlan.BIZ_POINT_PLAN, new OrderField[] { BizPointPlan.BIZ_POINT_PLAN.ID }, true);
        public static Index BIZ_POINT_TASK_ITEM_ORG_PRIMARY = Internal.createIndex("PRIMARY", BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG, new OrderField[] { BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.ID }, true);
        public static Index BIZ_POINT_TASK_ITEM_POINT_ORG_ID = Internal.createIndex("org_id", BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT, new OrderField[] { BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ORG_ID }, false);
        public static Index BIZ_POINT_TASK_ITEM_POINT_PATROL_POINT_ID = Internal.createIndex("patrol_point_id", BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT, new OrderField[] { BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.POINT_ID }, false);
        public static Index BIZ_POINT_TASK_ITEM_POINT_PATROL_TASK_ITEM_ID = Internal.createIndex("patrol_task_item_id", BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT, new OrderField[] { BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.POINT_TASK_ITEM_ID }, false);
        public static Index BIZ_POINT_TASK_ITEM_POINT_PRIMARY = Internal.createIndex("PRIMARY", BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT, new OrderField[] { BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ID }, true);
        public static Index BIZ_USER_KEEP_ONLINE_TIME_PRIMARY = Internal.createIndex("PRIMARY", BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME, new OrderField[] { BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ID }, true);
        public static Index BIZ_USER_ONLINE_TIME_PRIMARY = Internal.createIndex("PRIMARY", BizUserOnlineTime.BIZ_USER_ONLINE_TIME, new OrderField[] { BizUserOnlineTime.BIZ_USER_ONLINE_TIME.ID }, true);
    }
}
