/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator;


import com.mr.sa.generator.tables.BizAppUser;
import com.mr.sa.generator.tables.BizOrg;
import com.mr.sa.generator.tables.BizPatrolPoint;
import com.mr.sa.generator.tables.BizPointPlan;
import com.mr.sa.generator.tables.BizPointTaskItemOrg;
import com.mr.sa.generator.tables.BizPointTaskItemPoint;
import com.mr.sa.generator.tables.BizUserKeepOnlineTime;
import com.mr.sa.generator.tables.BizUserOnlineTime;
import com.mr.sa.generator.tables.records.BizAppUserRecord;
import com.mr.sa.generator.tables.records.BizOrgRecord;
import com.mr.sa.generator.tables.records.BizPatrolPointRecord;
import com.mr.sa.generator.tables.records.BizPointPlanRecord;
import com.mr.sa.generator.tables.records.BizPointTaskItemOrgRecord;
import com.mr.sa.generator.tables.records.BizPointTaskItemPointRecord;
import com.mr.sa.generator.tables.records.BizUserKeepOnlineTimeRecord;
import com.mr.sa.generator.tables.records.BizUserOnlineTimeRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>sa</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BizAppUserRecord> KEY_BIZ_APP_USER_PRIMARY = UniqueKeys0.KEY_BIZ_APP_USER_PRIMARY;
    public static final UniqueKey<BizAppUserRecord> KEY_BIZ_APP_USER_USERNAME_ = UniqueKeys0.KEY_BIZ_APP_USER_USERNAME_;
    public static final UniqueKey<BizOrgRecord> KEY_BIZ_ORG_PRIMARY = UniqueKeys0.KEY_BIZ_ORG_PRIMARY;
    public static final UniqueKey<BizOrgRecord> KEY_BIZ_ORG_CODE = UniqueKeys0.KEY_BIZ_ORG_CODE;
    public static final UniqueKey<BizPatrolPointRecord> KEY_BIZ_PATROL_POINT_PRIMARY = UniqueKeys0.KEY_BIZ_PATROL_POINT_PRIMARY;
    public static final UniqueKey<BizPointPlanRecord> KEY_BIZ_POINT_PLAN_PRIMARY = UniqueKeys0.KEY_BIZ_POINT_PLAN_PRIMARY;
    public static final UniqueKey<BizPointTaskItemOrgRecord> KEY_BIZ_POINT_TASK_ITEM_ORG_PRIMARY = UniqueKeys0.KEY_BIZ_POINT_TASK_ITEM_ORG_PRIMARY;
    public static final UniqueKey<BizPointTaskItemPointRecord> KEY_BIZ_POINT_TASK_ITEM_POINT_PRIMARY = UniqueKeys0.KEY_BIZ_POINT_TASK_ITEM_POINT_PRIMARY;
    public static final UniqueKey<BizUserKeepOnlineTimeRecord> KEY_BIZ_USER_KEEP_ONLINE_TIME_PRIMARY = UniqueKeys0.KEY_BIZ_USER_KEEP_ONLINE_TIME_PRIMARY;
    public static final UniqueKey<BizUserOnlineTimeRecord> KEY_BIZ_USER_ONLINE_TIME_PRIMARY = UniqueKeys0.KEY_BIZ_USER_ONLINE_TIME_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<BizAppUserRecord> KEY_BIZ_APP_USER_PRIMARY = Internal.createUniqueKey(BizAppUser.BIZ_APP_USER, "KEY_biz_app_user_PRIMARY", BizAppUser.BIZ_APP_USER.ID_);
        public static final UniqueKey<BizAppUserRecord> KEY_BIZ_APP_USER_USERNAME_ = Internal.createUniqueKey(BizAppUser.BIZ_APP_USER, "KEY_biz_app_user_username_", BizAppUser.BIZ_APP_USER.USERNAME_);
        public static final UniqueKey<BizOrgRecord> KEY_BIZ_ORG_PRIMARY = Internal.createUniqueKey(BizOrg.BIZ_ORG, "KEY_biz_org_PRIMARY", BizOrg.BIZ_ORG.ID);
        public static final UniqueKey<BizOrgRecord> KEY_BIZ_ORG_CODE = Internal.createUniqueKey(BizOrg.BIZ_ORG, "KEY_biz_org_code", BizOrg.BIZ_ORG.CODE);
        public static final UniqueKey<BizPatrolPointRecord> KEY_BIZ_PATROL_POINT_PRIMARY = Internal.createUniqueKey(BizPatrolPoint.BIZ_PATROL_POINT, "KEY_biz_patrol_point_PRIMARY", BizPatrolPoint.BIZ_PATROL_POINT.ID);
        public static final UniqueKey<BizPointPlanRecord> KEY_BIZ_POINT_PLAN_PRIMARY = Internal.createUniqueKey(BizPointPlan.BIZ_POINT_PLAN, "KEY_biz_point_plan_PRIMARY", BizPointPlan.BIZ_POINT_PLAN.ID);
        public static final UniqueKey<BizPointTaskItemOrgRecord> KEY_BIZ_POINT_TASK_ITEM_ORG_PRIMARY = Internal.createUniqueKey(BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG, "KEY_biz_point_task_item_org_PRIMARY", BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG.ID);
        public static final UniqueKey<BizPointTaskItemPointRecord> KEY_BIZ_POINT_TASK_ITEM_POINT_PRIMARY = Internal.createUniqueKey(BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT, "KEY_biz_point_task_item_point_PRIMARY", BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT.ID);
        public static final UniqueKey<BizUserKeepOnlineTimeRecord> KEY_BIZ_USER_KEEP_ONLINE_TIME_PRIMARY = Internal.createUniqueKey(BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME, "KEY_biz_user_keep_online_time_PRIMARY", BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME.ID);
        public static final UniqueKey<BizUserOnlineTimeRecord> KEY_BIZ_USER_ONLINE_TIME_PRIMARY = Internal.createUniqueKey(BizUserOnlineTime.BIZ_USER_ONLINE_TIME, "KEY_biz_user_online_time_PRIMARY", BizUserOnlineTime.BIZ_USER_ONLINE_TIME.ID);
    }
}
