/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator;


import com.mr.sa.generator.tables.BizAppUser;
import com.mr.sa.generator.tables.BizOrg;
import com.mr.sa.generator.tables.BizPatrolPoint;
import com.mr.sa.generator.tables.BizPointPlan;
import com.mr.sa.generator.tables.BizPointTaskItemOrg;
import com.mr.sa.generator.tables.BizPointTaskItemPoint;
import com.mr.sa.generator.tables.BizUserKeepOnlineTime;
import com.mr.sa.generator.tables.BizUserOnlineTime;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sa extends SchemaImpl {

    private static final long serialVersionUID = -197591550;

    /**
     * The reference instance of <code>sa</code>
     */
    public static final Sa SA = new Sa();

    /**
     * 用户
     */
    public final BizAppUser BIZ_APP_USER = com.mr.sa.generator.tables.BizAppUser.BIZ_APP_USER;

    /**
     * 组织
     */
    public final BizOrg BIZ_ORG = com.mr.sa.generator.tables.BizOrg.BIZ_ORG;

    /**
     * 巡防点
     */
    public final BizPatrolPoint BIZ_PATROL_POINT = com.mr.sa.generator.tables.BizPatrolPoint.BIZ_PATROL_POINT;

    /**
     * 巡防活动
     */
    public final BizPointPlan BIZ_POINT_PLAN = com.mr.sa.generator.tables.BizPointPlan.BIZ_POINT_PLAN;

    /**
     * 关系:巡防任务/巡防组织
     */
    public final BizPointTaskItemOrg BIZ_POINT_TASK_ITEM_ORG = com.mr.sa.generator.tables.BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG;

    /**
     * 关系:巡防任务/巡防组织
     */
    public final BizPointTaskItemPoint BIZ_POINT_TASK_ITEM_POINT = com.mr.sa.generator.tables.BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT;

    /**
     * The table <code>sa.biz_user_keep_online_time</code>.
     */
    public final BizUserKeepOnlineTime BIZ_USER_KEEP_ONLINE_TIME = com.mr.sa.generator.tables.BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME;

    /**
     * The table <code>sa.biz_user_online_time</code>.
     */
    public final BizUserOnlineTime BIZ_USER_ONLINE_TIME = com.mr.sa.generator.tables.BizUserOnlineTime.BIZ_USER_ONLINE_TIME;

    /**
     * No further instances allowed
     */
    private Sa() {
        super("sa", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BizAppUser.BIZ_APP_USER,
            BizOrg.BIZ_ORG,
            BizPatrolPoint.BIZ_PATROL_POINT,
            BizPointPlan.BIZ_POINT_PLAN,
            BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG,
            BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT,
            BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME,
            BizUserOnlineTime.BIZ_USER_ONLINE_TIME);
    }
}
