/*
 * This file is generated by jOOQ.
*/
package com.mr.sa.generator;


import com.mr.sa.generator.tables.BizAppUser;
import com.mr.sa.generator.tables.BizOrg;
import com.mr.sa.generator.tables.BizPatrolPoint;
import com.mr.sa.generator.tables.BizPointPlan;
import com.mr.sa.generator.tables.BizPointTaskItemOrg;
import com.mr.sa.generator.tables.BizPointTaskItemPoint;
import com.mr.sa.generator.tables.BizUserKeepOnlineTime;
import com.mr.sa.generator.tables.BizUserOnlineTime;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in sa
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户
     */
    public static final BizAppUser BIZ_APP_USER = com.mr.sa.generator.tables.BizAppUser.BIZ_APP_USER;

    /**
     * 组织
     */
    public static final BizOrg BIZ_ORG = com.mr.sa.generator.tables.BizOrg.BIZ_ORG;

    /**
     * 巡防点
     */
    public static final BizPatrolPoint BIZ_PATROL_POINT = com.mr.sa.generator.tables.BizPatrolPoint.BIZ_PATROL_POINT;

    /**
     * 巡防活动
     */
    public static final BizPointPlan BIZ_POINT_PLAN = com.mr.sa.generator.tables.BizPointPlan.BIZ_POINT_PLAN;

    /**
     * 关系:巡防任务/巡防组织
     */
    public static final BizPointTaskItemOrg BIZ_POINT_TASK_ITEM_ORG = com.mr.sa.generator.tables.BizPointTaskItemOrg.BIZ_POINT_TASK_ITEM_ORG;

    /**
     * 关系:巡防任务/巡防组织
     */
    public static final BizPointTaskItemPoint BIZ_POINT_TASK_ITEM_POINT = com.mr.sa.generator.tables.BizPointTaskItemPoint.BIZ_POINT_TASK_ITEM_POINT;

    /**
     * The table <code>sa.biz_user_keep_online_time</code>.
     */
    public static final BizUserKeepOnlineTime BIZ_USER_KEEP_ONLINE_TIME = com.mr.sa.generator.tables.BizUserKeepOnlineTime.BIZ_USER_KEEP_ONLINE_TIME;

    /**
     * The table <code>sa.biz_user_online_time</code>.
     */
    public static final BizUserOnlineTime BIZ_USER_ONLINE_TIME = com.mr.sa.generator.tables.BizUserOnlineTime.BIZ_USER_ONLINE_TIME;
}
